/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package actividad_5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void sumaTest() {
        App appTest = new App();
        assertEquals(3, appTest.sumar(1, 2));
    }
}
